# Generated by Django 5.0.1 on 2024-05-01 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_booked_delete_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booked',
        ),
    ]
